#!/bin/bash

#  Find/replace this variable =  sywtlg

# Spin up a new site inside Awesome Agency
terminus site:create --org=f43f78ff-e89e-4835-8896-14f7583706fa -- sywtlg sywtlg WordPress
# Install that site
terminus wp sitename.dev -- core install --url=dev.sitename.pantheonsite.io --title=WP-CLI_DEMO_Test --admin_user=dwayne --admin_password=Password1 --admin_email=dwayne@pantheon.io

#clean up
terminus wp sywtlg.dev -- theme delete twentysixteen twentyten twentyeleven twentytwelve twentythirteen twentyfourteen twentyfifteen
terminus wp sywtlg.dev -- theme update --all
terminus wp sywtlg.dev -- plugin delete akismet hello

#Install WP-CFM
terminus wp sywtlg.dev -- plugin install wp-cfm --activate

#put in the dumb emoji widget
terminus wp sywtlg.dev -- plugin install https://github.com/1dwaynemcdaniel/CIA-Emoji-WP-Plugin/archive/master.zip --activate


#terminus wp sywtlg.dev -- theme install omega
#terminus wp sywtlg.dev -- theme install me 
#terminus wp sywtlg.dev -- theme install altitude-lite --activate
#terminus wp sywtlg.dev -- scaffold child-theme childomega --parent_theme=omega --Activate
#terminus wp sywtlg.dev -- post generate --count=15 --post_date=2000-01-01
#terminus wp sywtlg.dev -- sidebar list
#terminus wp sywtlg.dev -- widget list sidebar-1
#terminus wp sywtlg.dev -- widget delete search-2
#terminus wp sywtlg.dev -- widget delete meta-2


#terminus wp mcdwaynedotcom.dev -- export --dir=/Users/dwaynemcdaniel/Desktop --post_type=post 

# generate some dummy posts
# wp post generate --count=15 --post_date=2000-01-01

# even better let's pull down some LorIpsum filler text and make dummy posts with that
# curl loripsum.net/api/5/short/headers/ul/bq | wp post generate --post_content --count=5

# create users with different roles
# wp user create bob bob@example.com --role=author
# wp user create jane jane@example.com --user_pass=“password” --role=administrator

# Install a new theme
# wp theme install https://downloads.wordpress.org/theme/primer.1.3.0.zip 

# Activate it
# wp theme activate primer

# Let's install a new theme and go ahead and activate it
# wp theme install universal --activate

# Let's install WooCommerce and activate it
# wp plugin install woocommerce
# wp plugin activate woocommerce

# Let's install Jetpack and activate it
# wp plugin install jetpack --activate

# wp plugin install wordfence duplicator

# wp plugin install WHAT ARE YOUR FAVES?

# What menus exist and are active?
# wp menu list

# let's make a new menu
#wp menu create "my-menu"

# let's make that the primary menu
# wp menu location assign my-menu primary

# Let's go ahead and make that menu link to a known address (google in this case)
# wp menu item add-custom my-menu Google http://google.com 

